version: '3'

services:
  user_db:
    image: postgres:alpine
    environment: 
      POSTGRES_USER: gorm
      POSTGRES_PASSWORD: gorm
      POSTGRES_DB: postgres
      POSTGRES_HOST: localhost
    ports:
      - 3306:3306