version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: backend
    restart: always
    platform: linux/amd64
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE:oddsdb
      - MYSQL_PASSWORD:root
    ports:
      - "3306:3306"