version: '3'

services:
  backend:
    image: mysql:latest
    container_name: backend
    restart: always
    platform: linux/amd64
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE:oddsdb
      - MYSQL_PASSWORD:root
      - MYSQL_TCP_PORT:3306
    ports:
      - "3306:3306"
  
  frontend: 
    container_name: frontend
    restart: unless-stoped